module.exports = {
    TranscribeController:require('./transcribe.controller'),
    FinanceController:require('./finance.controller'),
    JobsController:require('./jobs.controller'),
    CustomerCareController:require('./customerCare.controller'),
    TranslateController:require('./translate.controller'),
    GeneralController:require('./general.controller'),
    EcommerceController:require('./ecommerce.controller'),
    CategoryController:require('./category.controller'),
    SubCategoryController:require('./subcategory.controller'),
    ItemController:require('./item.controller'),
    HesaathiController: require('./hesaathi.controller'),
    StaffController: require('./staff.controller'),
    CustomerController:require('./customer.controller'),
    GrievancesController:require('./grievances.controller'),
    MessageController:require('./message.controller'),
    InteraktController:require('./interakt.controller'),
    DepartmentController:require('../client/department.controller'),
    DashboardController:require('./dashboard.controller'),
    RealEstateController:require('./realEstate.controller'),
    EnrollmentController:require('./enrollment.controller'),
    ONDCController:require('./ondc.controller'),
    InventoryController:require('./inventory.controller')
}