module.exports = {
    UserModel: require('./user').userModel,
    TranscribedFiles: require('./transcribedFiles').transcribedFilesModel,
    Queries: require('./queries').queriesModel,
    Jobs: require('./jobs').jobsModel,
    CustomerCare: require('./customerCare').customerCareModel,
    Finance: require('./finance').financeModel,
    General: require('./general').generalModel,
    Ecommerce: require('./ecommerce').ecommerceModel,
    Order:require('./order').orderModel,
    OrderItems:require('./orderItems').orderItemModel,
    Category:require('./category').categoryModel,
    SubCategory:require('./subcategory').subCategoryModel,
    Item:require('./item').itemModel,
    Hesaathi: require('./hesaathi').hesaathiModel,
    StaffModel : require('./staff').staffModel,
    Customer:require('./customer').customerModel,
    Grievances:require('./grievances').grievancesModel,
    GrievancesFileModel:require('./grievancesTranscription').GrievancesFilesModel,
    grievancesQueriesModel:require('./qrievancesQuery').grievancesQueriesModel,
    InteraktMessageModel: require('./interaktmessages').interaktModel,
    MatchingStatusModel:require('./matchingStatus').matchingStatusModel,
    OthersModel:require('./others').othersModel,
    EmployerModel:require('./employer').employerModel,
    CandidateModel:require('./candidate').candidateModel,
    DepartmentModel: require('./department').departmentModel,
    CustomerCareQueriesModel:require('./customercarequeries').customercarequeriesModel,
    CustomerCareTranscribedFiles:require('./customercaretranscription').customerCareTranscribedFilesModel,
    MatchingJobsStatusModel:require('./matchingJobsStatus').matchingJobsStatusModel,
    RealEstate:require('./realEstate').realEstateModel,
    RealEstateQueriesModel:require('./realEstateQueries').realEstateQueriesModel,
    RealEstateTranscriptionModel:require('./realEstateTranscriptions').realEstateTranscribedFilesModel,
    EnrollmentModel:require('./enrollment').enrollmentModel,
    ONDCModel:require('./ondc').ondcModel,
    ONDCTranscription:require('./ondcTranscription').ondcTranscribedFilesModel,
    ONDCDescriptionModel:require('./ondcDescriptions').ondcDescriptionModel,
    UploadRecords:require('./uploadRecords').uploadRecordsModel,
    ONDCTranscribedProductModel:require('./ondcProductTranscription').ondcTranscribedProductModel
}